name: alplaapp
description: "Dashboard Industrial para Alpla - GestiÃ³n de Paradas y Eficiencia"

version: 1.0.8+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  
  # UI & Design
  google_fonts: ^6.1.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  
  # Backend & Data
  supabase_flutter: ^2.5.6
  shared_preferences: ^2.2.3
  
  # Utils
  crypto: ^3.0.3
  uuid: ^4.4.0
  flutter_local_notifications: ^19.5.0
  http: ^1.6.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  dio: ^5.9.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  open_file: ^3.5.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


